### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by naveenr-btc**
Linked setup instruction to Labkey wiki

### CODE REVIEW

**Review by rohitn-boston — APPROVED** [review]

**Comment by labkey-adam** [comment]
👍

**Comment by labkey-adam** [comment]
You can delete the feature branch now. In most repos, we add a rule so this happens automatically.

**Comment by labkey-adam** [comment]
FYI: Once we are granted the right permissions, we will update the rules to auto-delete feature branches and automate the 21.3.x tagging & merges to develop.

**Comment by naveenr-btc** [comment]
Sure.

**Pull request merged**
